version: '3'
services:
  kadmin:
    build: kadmin/
    image: mans0954/kerberos-kadmin
    container_name: kadmin
    domainname: example.org
    volumes:
      - krb5kdc:/etc/krb5kdc
      - ./kadmin/krb5.conf:/etc/kadmin/krb5.conf
    networks:
      - example
    ports:
      - "749:749/tcp"
    depends_on:
      - kdc

  kdc:
    build: kdc/
    image: mans0954/kerberos-kdc
    container_name: kdc
    domainname: example.org
    volumes:
      - krb5kdc:/etc/krb5kdc
      - ./kdc/krb5.conf:/etc/kdc/krb5.conf
    networks:
      - example
    ports:
      - "88:88/udp"
      - "88:88/tcp" 

volumes:
  krb5kdc: {}

networks:
  example:
